// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS9DE5aHXgmJh-Ba6Qbm7wZf2g-a7_bxs',
    appId: '1:471695070277:web:7fac3002ad51e06704ff2c',
    messagingSenderId: '471695070277',
    projectId: 'chatapp-a1cde',
    authDomain: 'chatapp-a1cde.firebaseapp.com',
    storageBucket: 'chatapp-a1cde.appspot.com',
    measurementId: 'G-FVD56PWYSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJUVSRdIAHhoUcjV_PeIgj8kYiaz5HOxo',
    appId: '1:471695070277:android:100ee8c9ad2e8c9c04ff2c',
    messagingSenderId: '471695070277',
    projectId: 'chatapp-a1cde',
    storageBucket: 'chatapp-a1cde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQkkq35l2uvyxjVYqgCiNBXDCwbt53cKA',
    appId: '1:471695070277:ios:bc1e46f4f56ed57804ff2c',
    messagingSenderId: '471695070277',
    projectId: 'chatapp-a1cde',
    storageBucket: 'chatapp-a1cde.appspot.com',
    iosBundleId: 'com.example.mychat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQkkq35l2uvyxjVYqgCiNBXDCwbt53cKA',
    appId: '1:471695070277:ios:bc1e46f4f56ed57804ff2c',
    messagingSenderId: '471695070277',
    projectId: 'chatapp-a1cde',
    storageBucket: 'chatapp-a1cde.appspot.com',
    iosBundleId: 'com.example.mychat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS9DE5aHXgmJh-Ba6Qbm7wZf2g-a7_bxs',
    appId: '1:471695070277:web:f84851a2833e87bd04ff2c',
    messagingSenderId: '471695070277',
    projectId: 'chatapp-a1cde',
    authDomain: 'chatapp-a1cde.firebaseapp.com',
    storageBucket: 'chatapp-a1cde.appspot.com',
    measurementId: 'G-VFSYEJC98X',
  );
}
