// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAROyrNiUIR98Rr-vPe0kFyFjJitAMiUt4',
    appId: '1:634606246134:web:206757e13ab8d5f288b4d7',
    messagingSenderId: '634606246134',
    projectId: 'chatapp-dbadd',
    authDomain: 'chatapp-dbadd.firebaseapp.com',
    storageBucket: 'chatapp-dbadd.appspot.com',
    measurementId: 'G-9QEF44SK3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcAbzas7tIzUbR5gRdLIkd-vLkODRdd8E',
    appId: '1:634606246134:android:4100706b1adebb3d88b4d7',
    messagingSenderId: '634606246134',
    projectId: 'chatapp-dbadd',
    storageBucket: 'chatapp-dbadd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVyj_xN0MGbB01F3qIDe_KRppQZutTH7U',
    appId: '1:634606246134:ios:78ed170436d7302788b4d7',
    messagingSenderId: '634606246134',
    projectId: 'chatapp-dbadd',
    storageBucket: 'chatapp-dbadd.appspot.com',
    iosBundleId: 'com.example.mychat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVyj_xN0MGbB01F3qIDe_KRppQZutTH7U',
    appId: '1:634606246134:ios:78ed170436d7302788b4d7',
    messagingSenderId: '634606246134',
    projectId: 'chatapp-dbadd',
    storageBucket: 'chatapp-dbadd.appspot.com',
    iosBundleId: 'com.example.mychat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAROyrNiUIR98Rr-vPe0kFyFjJitAMiUt4',
    appId: '1:634606246134:web:1be4bf53cf1abeed88b4d7',
    messagingSenderId: '634606246134',
    projectId: 'chatapp-dbadd',
    authDomain: 'chatapp-dbadd.firebaseapp.com',
    storageBucket: 'chatapp-dbadd.appspot.com',
    measurementId: 'G-D4S07XDHWT',
  );

}